name: learning_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dotenv: ^4.2.0
  http: ^1.2.2
  # path: ^1.8.0